# Generated by Django 5.1.15 on 2026-08-27 09:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0004_connector_offline_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha matn")),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/', verbose_name='Rasm')),
                ('link_url', models.URLField(blank=True, verbose_name='Havola')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Umumiy'), ('charging', 'Zaryadlash'), ('payment', "To'lov"), ('account', 'Hisob')], default='general', max_length=20, verbose_name="Bo'lim")),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'FAQ savoli',
                'verbose_name_plural': 'FAQ savollari',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('privacy', 'Maxfiylik siyosati'), ('terms', 'Foydalanish shartlari'), ('about', 'Ilova haqida')], max_length=20, unique=True, verbose_name='Sahifa')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='Matn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huquqiy sahifa',
                'verbose_name_plural': 'Huquqiy sahifalar',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Yuridik nomi')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name="Mas'ul shaxs")),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('commission_percent', models.PositiveSmallIntegerField(default=0, help_text='VoltMax ushlab qoladigan ulush', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Komissiya (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='VoltMax', max_length=100, verbose_name='Ilova nomi')),
                ('support_phone', models.CharField(blank=True, max_length=30, verbose_name="Qo'llab-quvvatlash telefoni")),
                ('support_telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Yoqilsa mobil ilovaga tegishli ogohlantirish ko'rsatiladi", verbose_name='Texnik ishlar rejimi')),
                ('default_price_per_kwh', models.PositiveIntegerField(default=1200, verbose_name="Standart narx (so'm/kVt·s)")),
                ('default_parking_fee_per_min', models.PositiveIntegerField(default=500, verbose_name="Parkovka tarifi (so'm/daq)")),
                ('min_topup', models.PositiveIntegerField(default=10000, verbose_name="Minimal to'ldirish (so'm)")),
                ('max_topup', models.PositiveIntegerField(default=5000000, verbose_name="Maksimal to'ldirish (so'm)")),
                ('payme_enabled', models.BooleanField(default=True, verbose_name='Payme yoqilgan')),
                ('click_enabled', models.BooleanField(default=True, verbose_name='Click yoqilgan')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push bildirishnomalar')),
                ('notify_charging_complete', models.BooleanField(default=True, verbose_name='Zaryad tugaganda xabar')),
                ('notify_parking_started', models.BooleanField(default=True, verbose_name='Parkovka boshlanganda xabar')),
                ('notify_low_balance', models.BooleanField(default=True, verbose_name='Balans kamayganda xabar')),
                ('otp_ttl_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='OTP amal qilish muddati (daq)')),
                ('otp_max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='OTP urinishlar chegarasi')),
                ('session_timeout_minutes', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Panel sessiyasi muddati (daq)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tizim sozlamalari',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('discount_type', models.CharField(choices=[('percent', 'Foiz (%)'), ('fixed', "Belgilangan summa (so'm)")], default='percent', max_length=10, verbose_name='Chegirma turi')),
                ('discount_value', models.PositiveIntegerField(default=0, verbose_name='Chegirma qiymati')),
                ('promo_code', models.CharField(blank=True, help_text="Bo'sh bo'lsa aksiya avtomatik qo'llanadi", max_length=40, verbose_name='Promo-kod')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanishi')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugashi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stations', models.ManyToManyField(blank=True, help_text="Bo'sh — barcha stansiyalarda amal qiladi", related_name='offers', to='stations.station', verbose_name='Stansiyalar')),
            ],
            options={
                'verbose_name': 'Aksiya',
                'verbose_name_plural': 'Aksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
