# Generated by Django 5.1.15 on 2026-08-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_known_rfid',
            field=models.BooleanField(default=False, help_text="Yoqilsa, ro'yxatda yo'q yoki tasdiqlanmagan karta rad etiladi", verbose_name='Faqat tasdiqlangan RFID kartalar'),
        ),
    ]
