# Generated by Django 5.1.15 on 2026-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_sitesettings_require_known_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='org_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tashkilot manzili'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_bank_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tashkilot hisob raqami'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_bank_mfo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tashkilot MFO'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tashkilot banki'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_director',
            field=models.CharField(blank=True, max_length=150, verbose_name='Rahbar (F.I.Sh.)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tashkilot STIR'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='org_legal_name',
            field=models.CharField(blank=True, help_text="Shartnomada ko'rsatiladi, masalan: VoltMax MChJ", max_length=250, verbose_name="Tashkilotning to'liq nomi"),
        ),
    ]
