# Generated by Django 5.1.15 on 2026-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_sitesettings_org_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Bo'lim sarlavhasi")),
                ('body', models.TextField(help_text="Har bir satr — alohida band. «- » bilan boshlangan satr oldingi bandning ichki bandi bo'ladi.", verbose_name='Bandlar')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa bo'lim saqlanadi, lekin hujjatga tushmaydi", verbose_name='Shartnomaga kiritilsin')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Shartnoma bo'limi",
                'verbose_name_plural': "Shartnoma bo'limlari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contract_appendix_note',
            field=models.CharField(default='Kartalar Buyurtmachiga topshirildi, Buyurtmachi ularni qabul qildi.', max_length=300, verbose_name='Ilova ostidagi izoh'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contract_city',
            field=models.CharField(default='Toshkent sh.', max_length=100, verbose_name='Tuzilgan joyi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contract_preamble',
            field=models.TextField(default="{ijrochi} nomidan Ustavga asosan ish yurituvchi rahbar {ijrochi_rahbari} (keyingi o'rinlarda — «Ijrochi») bir tomondan va {buyurtmachi} nomidan Ustavga asosan ish yurituvchi rahbar {buyurtmachi_rahbari} (keyingi o'rinlarda — «Buyurtmachi») ikkinchi tomondan, quyidagilar to'g'risida ushbu shartnomani tuzdilar:", help_text="O'rin egallovchilar ishlaydi: {ijrochi}, {buyurtmachi} va boshqalar", verbose_name='Kirish qismi (preambula)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contract_title',
            field=models.CharField(default='ELEKTROMOBILLARNI ZARYADLASH XIZMATLARI SHARTNOMASI', max_length=200, verbose_name='Shartnoma sarlavhasi'),
        ),
    ]
