# Generated by Django 5.1.15 on 2026-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_contractsection_sitesettings_contract_appendix_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('source', models.CharField(choices=[('google', 'Google Calendar'), ('manual', "Qo'lda kiritilgan")], default='manual', max_length=10)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bayram kuni',
                'verbose_name_plural': 'Bayram kunlari',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='holiday_ics_url',
            field=models.URLField(blank=True, default='https://calendar.google.com/calendar/ical/uz.uz%23holiday%40group.v.calendar.google.com/public/basic.ics', help_text="Google Calendar'ning ochiq ICS manzili", max_length=300, verbose_name='Bayramlar kalendari (ICS)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='holidays_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
