# Generated by Django 5.1.15 on 2026-08-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_providers(apps, schema_editor):
    """Eski bayroqlar (`payme_enabled`, `click_enabled`) o'rniga yozuv.

    Bayroqlar o'chirilishidan oldin ishlaydi, shuning uchun qaysi tizim
    yoqilgani saqlanib qoladi.
    """
    SiteSettings = apps.get_model('management', 'SiteSettings')
    PaymentProvider = apps.get_model('management', 'PaymentProvider')

    current = SiteSettings.objects.first()
    known = [('payme', 'Payme', getattr(current, 'payme_enabled', True) if current else True),
             ('click', 'Click', getattr(current, 'click_enabled', True) if current else True)]
    for order, (code, name, enabled) in enumerate(known, 1):
        PaymentProvider.objects.get_or_create(
            code=code, defaults={'name': name, 'is_active': enabled, 'order': order})


def drop_providers(apps, schema_editor):
    PaymentProvider = apps.get_model('management', 'PaymentProvider')
    PaymentProvider.objects.filter(code__in=['payme', 'click']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_holiday_sitesettings_holiday_ics_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.SlugField(help_text='Tizimdagi nomi: payme, click, uzum. Integratsiya shunga qaraydi', max_length=40, unique=True, verbose_name='Kod')),
                ('merchant_id', models.CharField(blank=True, help_text="To'lov tashkiloti bergan identifikator", max_length=100, verbose_name='Merchant / Kassa ID')),
                ('secret_key', models.CharField(blank=True, help_text="Panelda to'liq ko'rsatilmaydi", max_length=200, verbose_name='Maxfiy kalit')),
                ('endpoint_url', models.URLField(blank=True, max_length=300, verbose_name='Manzil (endpoint)')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa mobil ilovada bu usul ko'rinmaydi", verbose_name='Yoqilgan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "To'lov tashkiloti",
                'verbose_name_plural': "To'lov tashkilotlari",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(create_providers, drop_providers),
        migrations.RemoveField(
            model_name='sitesettings',
            name='click_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='payme_enabled',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_session_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text="0 — cheklanmagan. Unutilgan sessiya kun bo'yi hisoblanib ketmasin", verbose_name='Sessiyaning eng uzun davomiyligi (daq)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_balance_to_start',
            field=models.PositiveIntegerField(default=0, help_text="Balans shundan kam bo'lsa sessiya boshlanmaydi", verbose_name="Zaryadlash uchun minimal balans (so'm)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='parking_grace_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Zaryad tugagach shu vaqt ichida parkovka haqi olinmaydi', verbose_name='Parkovka imtiyoz vaqti (daq)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_all_day',
            field=models.BooleanField(default=True, help_text="O'chirilsa quyidagi soatlar amal qiladi", verbose_name='Kunu tun ishlaydi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_end',
            field=models.TimeField(default='22:00', verbose_name='Ish tugashi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_start',
            field=models.TimeField(default='08:00', verbose_name='Ish boshlanishi'),
        ),
        migrations.CreateModel(
            name='SettingsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=40, verbose_name="Bo'lim")),
                ('field', models.CharField(max_length=60, verbose_name='Maydon')),
                ('label', models.CharField(max_length=150, verbose_name='Nomi')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Eski qiymat')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Yangi qiymat')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Sozlama o'zgarishi",
                'verbose_name_plural': "Sozlama o'zgarishlari",
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['-changed_at'], name='management__changed_6c482c_idx')],
            },
        ),
    ]
