# Generated by Django 5.1.15 on 2026-08-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_paymentprovider_remove_sitesettings_click_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('station_down', 'Stansiya ishlamay qoldi'), ('station_up', 'Stansiya tuzatildi'), ('charging_complete', 'Zaryad tugadi'), ('parking_started', 'Parkovka boshlandi'), ('low_balance', 'Balans kamaydi'), ('system', 'Umumiy xabar')], max_length=30, unique=True, verbose_name='Hodisa')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('body', models.CharField(max_length=400, verbose_name='Matn')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa bu hodisa bo'yicha xabar yozilmaydi", verbose_name='Yuborilsin')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bildirishnoma shabloni',
                'verbose_name_plural': 'Bildirishnoma shablonlari',
                'ordering': ['event'],
            },
        ),
    ]
