# Generated by Django 5.1.15 on 2026-08-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_notificationtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('station_down', 'Stansiya ishlamay qoldi'), ('station_up', 'Stansiya tuzatildi'), ('charging_complete', 'Zaryad tugadi'), ('parking_started', 'Parkovka boshlandi'), ('low_balance', 'Balans kamaydi'), ('session_timeout', 'Sessiya vaqti tugadi'), ('system', 'Umumiy xabar')], max_length=30, unique=True, verbose_name='Hodisa'),
        ),
    ]
