# Generated by Django 5.1.15 on 2026-08-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_notificationtemplate_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='push_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='push_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telefonga yuborilgan'),
        ),
    ]
