# Generated by Django 5.1.15 on 2026-08-31 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_usernotification_push_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('card', 'RFID karta'), ('wallet', 'Hamyon'), ('invoice', "To'lov hisobi"), ('company', 'Korporativ mijoz'), ('session', 'Sessiya'), ('station', 'Stansiya'), ('maintenance', 'Profilaktika'), ('device', "Qurilma buyrug'i"), ('other', 'Boshqa')], default='other', max_length=20, verbose_name="Bo'lim")),
                ('title', models.CharField(max_length=150, verbose_name='Amal')),
                ('detail', models.CharField(blank=True, max_length=400, verbose_name='Tafsilot')),
                ('target_url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
            ],
            options={
                'verbose_name': 'Amal yozuvi',
                'verbose_name_plural': 'Amallar jurnali',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='management__created_42f618_idx'), models.Index(fields=['action', '-created_at'], name='management__action_1477a3_idx')],
            },
        ),
    ]
