# Generated by Django 5.1.15 on 2026-08-31 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy')),
                ('gross', models.PositiveIntegerField(default=0, verbose_name="Umumiy tushum (so'm)")),
                ('commission_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Komissiya (%)')),
                ('commission', models.PositiveIntegerField(default=0, verbose_name="Bizning ulush (so'm)")),
                ('amount', models.PositiveIntegerField(default=0, verbose_name="Hamkorga (so'm)")),
                ('sessions', models.PositiveIntegerField(default=0, verbose_name='Sessiyalar')),
                ('kwh', models.FloatField(default=0, verbose_name='Energiya (kVt·s)')),
                ('status', models.CharField(choices=[('pending', "To'lanmagan"), ('paid', "To'langan")], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=50, verbose_name="To'lov topshiriqnomasi №")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='management.partner', verbose_name='Hamkor')),
            ],
            options={
                'verbose_name': 'Hamkor hisob-kitobi',
                'verbose_name_plural': 'Hamkorlar hisob-kitobi',
                'ordering': ['-year', '-month', 'partner__name'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'year', 'month'), name='unique_partner_period')],
            },
        ),
    ]
