# Generated by Django 5.1.15 on 2026-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_partnerpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Vazifa')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi ishlagani')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi muvaffaqiyat')),
                ('last_summary', models.CharField(blank=True, max_length=255, verbose_name='Natija')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Xato')),
                ('fail_streak', models.PositiveIntegerField(default=0, verbose_name='Ketma-ket xato')),
                ('runs', models.PositiveIntegerField(default=0, verbose_name='Jami ishlagani')),
            ],
            options={
                'verbose_name': 'Vazifa holati',
                'verbose_name_plural': 'Vazifalar holati',
                'ordering': ['name'],
            },
        ),
    ]
