# Generated by Django 5.1.15 on 2026-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='panel_lockout_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Chegara tugagach shu vaqt davomida kirish yopiladi', verbose_name='Bloklash muddati (daq)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='panel_max_attempts',
            field=models.PositiveSmallIntegerField(default=5, help_text="0 — chegara yo'q (tavsiya etilmaydi)", verbose_name='Panel parol urinishlari chegarasi'),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Login')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('successful', models.BooleanField(default=False, verbose_name='Muvaffaqiyatli')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='Brauzer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Kirish urinishi',
                'verbose_name_plural': 'Kirish urinishlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', 'ip', 'created_at'], name='management__usernam_e21f0d_idx')],
            },
        ),
    ]
