# Generated by Django 5.1.15 on 2026-08-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_sitesettings_panel_lockout_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='otp_gateway_token',
            field=models.CharField(blank=True, help_text="Telegram Gateway tokeni. Bo'sh bo'lsa server sozlamasidagi qiymat ishlatiladi", max_length=200, verbose_name='OTP shlyuzi kaliti'),
        ),
    ]
