# Generated by Django 5.1.15 on 2026-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_sitesettings_otp_gateway_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_ocpp_auth',
            field=models.BooleanField(default=True, help_text="O'chirilsa parolsiz charger ham ulana oladi — tavsiya etilmaydi", verbose_name='OCPP paroli majburiy'),
        ),
    ]
