# Generated by Django 5.1.15 on 2026-08-31 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_sitesettings_require_ocpp_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_2fa_for_admins',
            field=models.BooleanField(default=False, help_text='Yoqilsa superuser hisoblar telefon kodisiz kira olmaydi', verbose_name='Administratorlarga ikki bosqichli kirish'),
        ),
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64, verbose_name='Maxfiy kalit')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('backup_hashes', models.JSONField(blank=True, default=list, verbose_name='Zaxira kodlari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Ikki bosqichli kirish',
                'verbose_name_plural': 'Ikki bosqichli kirish',
            },
        ),
    ]
