# Generated by Django 5.2.17 on 2026-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_sitesettings_require_2fa_for_admins_twofactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Telegram ishlamasa kod SMS bilan yuboriladi', verbose_name='SMS yuborish'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_login',
            field=models.CharField(blank=True, help_text='Eskiz.uz hisobingiz elektron pochtasi', max_length=150, verbose_name='SMS xizmati logini'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMS xizmati paroli'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_sender',
            field=models.CharField(blank=True, help_text="Eskiz tasdiqlagan nom. Bo'sh bo'lsa sinov rejimi (4546)", max_length=20, verbose_name="Jo'natuvchi nomi"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_token',
            field=models.TextField(blank=True, verbose_name='SMS tokeni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_token_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
