# Generated by Django 5.2.17 on 2026-08-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_sitesettings_sms_enabled_sitesettings_sms_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sms_otp_text',
            field=models.CharField(blank=True, help_text="{code} — kod o'rni. Eskiz'da bu matn OLDINDAN tasdiqlangan bo'lishi kerak", max_length=160, verbose_name='Kod matni (SMS)'),
        ),
    ]
