# Generated by Django 5.2.17 on 2026-08-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_sitesettings_sms_otp_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mail_alerts_to',
            field=models.CharField(blank=True, help_text="Bo'sh bo'lsa ogohlantirish yuborilmaydi", max_length=400, verbose_name='Ogohlantirish manzillari'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_enabled',
            field=models.BooleanField(default=False, verbose_name='Pochta yuborish'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_from',
            field=models.CharField(blank=True, help_text='VoltMax <billing@voltmax.uz>', max_length=200, verbose_name="Jo'natuvchi manzili"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_host',
            field=models.CharField(blank=True, help_text='masalan: smtp.gmail.com', max_length=150, verbose_name='SMTP server'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parol'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_port',
            field=models.PositiveSmallIntegerField(default=587, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_use_tls',
            field=models.BooleanField(default=True, help_text="587-portda odatda yoqiladi, 465-portda o'chiriladi", verbose_name='TLS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_user',
            field=models.CharField(blank=True, max_length=150, verbose_name='Foydalanuvchi'),
        ),
    ]
