# Generated by Django 5.1.15 on 2026-08-24 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('charging', 'Zaryadlanmoqda'), ('completed', 'Tugallandi'), ('stopped', "To'xtatildi"), ('error', 'Xatolik')], default='charging', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('start_percent', models.PositiveIntegerField()),
                ('power_kw', models.PositiveIntegerField()),
                ('price_per_kwh', models.PositiveIntegerField()),
                ('voltage_v', models.FloatField(default=400.0)),
                ('parking_fee_per_min', models.PositiveIntegerField(default=500)),
                ('connector_label', models.CharField(default='A', max_length=10)),
                ('final_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('final_kwh_charged', models.FloatField(blank=True, null=True)),
                ('final_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('connector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='stations.connector')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zaryadlash sessiyasi',
                'verbose_name_plural': 'Zaryadlash sessiyalari',
                'ordering': ['-started_at'],
            },
        ),
    ]
