# Generated by Django 5.1.15 on 2026-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='id_tag',
            field=models.CharField(blank=True, help_text='OCPP Authorize/StartTransaction idTag', max_length=50),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Haqiqiy charger orqali (OCPP) boshlangan sessiyami'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='live_meter_wh',
            field=models.PositiveIntegerField(blank=True, help_text='Oxirgi MeterValues hisoblagich (Wh)', null=True),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='meter_start_wh',
            field=models.PositiveIntegerField(blank=True, help_text='Boshlanishdagi hisoblagich (Wh)', null=True),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='meter_stop_wh',
            field=models.PositiveIntegerField(blank=True, help_text='Tugashdagi hisoblagich (Wh)', null=True),
        ),
    ]
