# Generated by Django 5.1.15 on 2026-08-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_chargingsession_id_tag_chargingsession_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='final_parking_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='final_parking_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
