# Generated by Django 5.1.15 on 2026-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_chargingsession_final_parking_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='parking_billed_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='parking_billed_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
