# Generated by Django 5.1.15 on 2026-08-30 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vehicle_vin'),
        ('sessions_app', '0004_chargingsession_parking_billed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.vehicle'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='vehicle_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN'),
        ),
        migrations.CreateModel(
            name='SessionMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('voltage_v', models.FloatField(blank=True, help_text='Kuchlanish, V', null=True)),
                ('current_a', models.FloatField(blank=True, help_text='Tok, A', null=True)),
                ('power_kw', models.FloatField(blank=True, help_text='Quvvat, kVt', null=True)),
                ('energy_wh', models.FloatField(blank=True, help_text='Hisoblagich, Wh', null=True)),
                ('soc_percent', models.FloatField(blank=True, help_text='Batareya foizi', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sessions_app.chargingsession')),
            ],
            options={
                'verbose_name': "O'lchov",
                'verbose_name_plural': "O'lchovlar",
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['session', 'recorded_at'], name='sessions_ap_session_a306bc_idx')],
            },
        ),
    ]
