# Generated by Django 5.1.15 on 2026-08-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0005_chargingsession_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='stop_reason',
            field=models.CharField(blank=True, help_text='OCPP StopTransaction reason (EVDisconnected, PowerLoss, Remote, ...)', max_length=30, verbose_name='Tugash sababi'),
        ),
        migrations.AddField(
            model_name='sessionmeterreading',
            name='current_offered_a',
            field=models.FloatField(blank=True, help_text='Taklif qilingan tok, A', null=True),
        ),
        migrations.AddField(
            model_name='sessionmeterreading',
            name='frequency_hz',
            field=models.FloatField(blank=True, help_text='Chastota, Hz', null=True),
        ),
        migrations.AddField(
            model_name='sessionmeterreading',
            name='power_offered_kw',
            field=models.FloatField(blank=True, help_text='Taklif qilingan quvvat, kVt', null=True),
        ),
        migrations.AddField(
            model_name='sessionmeterreading',
            name='temperature_c',
            field=models.FloatField(blank=True, help_text='Harorat, °C', null=True),
        ),
        migrations.AddField(
            model_name='sessionmeterreading',
            name='voltage_l1_v',
            field=models.FloatField(blank=True, help_text='L1 kuchlanishi, V', null=True),
        ),
        migrations.AddField(
            model_name='sessionmeterreading',
            name='voltage_l2_v',
            field=models.FloatField(blank=True, help_text='L2 kuchlanishi, V', null=True),
        ),
        migrations.AddField(
            model_name='sessionmeterreading',
            name='voltage_l3_v',
            field=models.FloatField(blank=True, help_text='L3 kuchlanishi, V', null=True),
        ),
    ]
