# Generated by Django 5.1.15 on 2026-08-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_partnerpayout'),
        ('sessions_app', '0006_chargingsession_stop_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='base_price_per_kwh',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chegirmasiz narx'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='management.offer', verbose_name='Aksiya'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='price_label',
            field=models.CharField(blank=True, help_text='Masalan: Tungi tarif · Bahorgi aksiya', max_length=200, verbose_name='Narx izohi'),
        ),
    ]
