# Generated by Django 5.1.15 on 2026-08-31 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0007_chargingsession_base_price_per_kwh_and_more'),
        ('stations', '0010_tariffwindow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_promos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kutilayotgan promo-kod',
                'verbose_name_plural': 'Kutilayotgan promo-kodlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
