# Generated by Django 5.2.17 on 2026-08-31 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0008_pendingpromo'),
        ('stations', '0011_station_ocpp_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteStartIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Promo-kod')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_start_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Masofadan boshlash so'rovi",
                'verbose_name_plural': "Masofadan boshlash so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PendingPromo',
        ),
    ]
