# Generated by Django 5.1.15 on 2026-08-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Foydalanuvchi bergan nom, masalan "Kundalik mashinam"', max_length=100)),
                ('make', models.CharField(blank=True, help_text='Ishlab chiqaruvchi, masalan Chevrolet', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Model, masalan Bolt EV', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_capacity_kwh', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Zaryadlash sessiyalarida standart tanlanadigan mashina')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transport vositasi',
                'verbose_name_plural': 'Transport vositalari',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
