# Generated by Django 5.1.15 on 2026-08-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Kuzov raqami — 17 belgi. Sessiya tarixida ham saqlanadi.', max_length=17, verbose_name='VIN'),
        ),
    ]
