# Generated by Django 5.1.15 on 2026-08-30 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vehicle_vin'),
        ('stations', '0009_connector_power_limit_kw_alter_connector_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(help_text="Kartaning OCPP identifikatori — chargerda o'qilgani", max_length=20, unique=True, verbose_name='Karta raqami (idTag)')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Nomi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('blocked', 'Bloklangan'), ('pending', 'Tasdiqlanmagan')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('first_seen_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stations.station')),
                ('user', models.ForeignKey(blank=True, help_text="Bo'sh qoldirilsa — xizmat kartasi", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'RFID karta',
                'verbose_name_plural': 'RFID kartalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
