# Generated by Django 5.1.15 on 2026-08-30 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rfidcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='blocked_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nomi')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name="Mas'ul shaxs")),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='STIR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Korporativ mijoz',
                'verbose_name_plural': 'Korporativ mijozlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='accounts.company', verbose_name='Korporativ mijoz'),
        ),
    ]
