# Generated by Django 5.1.15 on 2026-08-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rfidcard_blocked_by_owner_company_rfidcard_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, help_text='20 xonali hisob raqami', max_length=30, verbose_name='Hisob raqami'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_mfo',
            field=models.CharField(blank=True, max_length=10, verbose_name='MFO'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank nomi'),
        ),
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.CharField(blank=True, max_length=150, verbose_name='Rahbar'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Yuridik manzil'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Shartnomadagi rasmiy nom, masalan: "VoltMax Servis" MChJ', max_length=250, verbose_name="To'liq yuridik nomi"),
        ),
        migrations.AddField(
            model_name='company',
            name='oked',
            field=models.CharField(blank=True, max_length=20, verbose_name='OKED'),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_code',
            field=models.CharField(blank=True, help_text="QQS to'lovchisi bo'lsa — registratsiya kodi", max_length=20, verbose_name='QQS kodi'),
        ),
    ]
