# Generated by Django 5.1.15 on 2026-08-30 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_bank_account_company_bank_mfo_and_more'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Hisob raqami')),
                ('amount', models.PositiveIntegerField(verbose_name="Summa (so'm)")),
                ('purpose', models.CharField(default="Elektromobillarni zaryadlash xizmati uchun avans to'lovi", max_length=255, verbose_name="To'lov maqsadi")),
                ('status', models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=10)),
                ('issued_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Yozilgan sana')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Qayd etilgan vaqt')),
                ('payment_ref', models.CharField(blank=True, help_text="Bank o'tkazmasidagi hujjat raqami", max_length=50, verbose_name="To'lov topshiriqnomasi №")),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name="Bankdagi o'tkazma sanasi")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.company', verbose_name='Korporativ mijoz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='wallet.transaction')),
            ],
            options={
                'verbose_name': "To'lov hisobi",
                'verbose_name_plural': "To'lov hisoblari",
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['company', '-issued_at'], name='accounts_co_company_3d6961_idx')],
            },
        ),
    ]
