# Generated by Django 5.1.15 on 2026-08-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otpcode_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='daily_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Bo'sh — kunlik chegara yo'q", null=True, verbose_name="Kunlik chegara (so'm)"),
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='monthly_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Bo'sh — oylik chegara yo'q", null=True, verbose_name="Oylik chegara (so'm)"),
        ),
    ]
