# Generated by Django 5.2.17 on 2026-08-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rfidcard_daily_limit_rfidcard_monthly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='sent_via',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('sms', 'SMS')], max_length=20, verbose_name='Qaysi kanal bilan'),
        ),
    ]
