# Generated by Django 5.2.17 on 2026-08-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_otpcode_sent_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Elektron pochta'),
        ),
    ]
