# Generated by Django 5.1.15 on 2026-08-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('charger_type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], default='DC', max_length=2)),
                ('power_kw', models.PositiveIntegerField(help_text='Stansiyaning umumiy quvvati (kVt)')),
                ('price_per_kwh', models.PositiveIntegerField(help_text="Joriy narx, so'm/kVt-soat")),
                ('original_price_per_kwh', models.PositiveIntegerField(blank=True, help_text="Chegirmagacha bo'lgan narx (bo'sh — chegirma yo'q)", null=True)),
                ('status', models.CharField(choices=[('available', "Bo'sh"), ('busy', 'Band'), ('offline', 'Ishlamayapti')], default='available', max_length=10)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stations/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stansiya',
                'verbose_name_plural': 'Stansiyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StationAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('oil', 'Moy'), ('wifi', 'Wi-Fi'), ('coffee', 'Kofe'), ('lounge', 'Dam olish xonasi')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='stations.station')),
            ],
            options={
                'verbose_name': 'Qulaylik',
                'verbose_name_plural': 'Qulayliklar',
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Masalan: A, B', max_length=10)),
                ('type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], default='DC', max_length=2)),
                ('power_kw', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', "Bo'sh"), ('charging', 'Zaryadlanmoqda'), ('offline', 'Ishlamayapti')], default='available', max_length=10)),
                ('charging_percent', models.PositiveIntegerField(blank=True, help_text="Faqat status='charging' bo'lganda — real vaqtda telemetriyadan keladi", null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='stations.station')),
            ],
            options={
                'verbose_name': 'Ulagich',
                'verbose_name_plural': 'Ulagichlar',
                'ordering': ['label'],
                'unique_together': {('station', 'label')},
            },
        ),
    ]
