# Generated by Django 5.1.15 on 2026-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connector',
            unique_together={('station', 'label')},
        ),
        migrations.AddField(
            model_name='connector',
            name='ocpp_connector_id',
            field=models.PositiveIntegerField(blank=True, help_text='Chargerdagi raqamli ulagich ID (OCPP connectorId), masalan: 1', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='ocpp_id',
            field=models.CharField(blank=True, help_text="Charger o'zini WebSocket ulanishda shu ID bilan tanishtiradi (masalan: CP-001)", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='station',
            name='ocpp_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='connector',
            unique_together={('station', 'label'), ('station', 'ocpp_connector_id')},
        ),
    ]
