# Generated by Django 5.1.15 on 2026-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='offline_reason',
            field=models.CharField(blank=True, help_text="status='offline' bo'lganda foydalanuvchiga ko'rsatiladigan sabab (OCPP errorCode yoki qo'lda)", max_length=200),
        ),
        migrations.AddField(
            model_name='connector',
            name='parking_started_at',
            field=models.DateTimeField(blank=True, help_text='Pullik parkovka rejimi boshlangan vaqt (kabel uzilmagan)', null=True),
        ),
    ]
