# Generated by Django 5.1.15 on 2026-08-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('stations', '0004_connector_offline_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='management.partner', verbose_name='Hamkor'),
        ),
    ]
