# Generated by Django 5.1.15 on 2026-08-30 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_station_central_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('connector', 'Ulagich nosozligi'), ('station', "Charger bilan aloqa yo'q")], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('resolved', 'Tuzatilgan')], db_index=True, default='open', max_length=10)),
                ('source', models.CharField(choices=[('ocpp', 'Qurilmadan'), ('manual', "Qo'lda")], default='ocpp', max_length=8)),
                ('reason', models.CharField(max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_notified_at', models.DateTimeField(blank=True, null=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='stations.connector')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='stations.station')),
            ],
            options={
                'verbose_name': 'Nosozlik',
                'verbose_name_plural': 'Nosozliklar',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', '-opened_at'], name='stations_ma_status_c00395_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('connector',), name='unique_open_issue_per_connector'), models.UniqueConstraint(condition=models.Q(('connector__isnull', True), ('status', 'open')), fields=('station',), name='unique_open_issue_per_station')],
            },
        ),
    ]
