# Generated by Django 5.1.15 on 2026-08-30 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_maintenanceissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='Ishlab chiqaruvchi')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriya raqami')),
                ('charge_box_serial', models.CharField(blank=True, max_length=100, verbose_name='Korpus seriyasi')),
                ('firmware_version', models.CharField(blank=True, max_length=100, verbose_name='Proshivka')),
                ('iccid', models.CharField(blank=True, max_length=40, verbose_name='SIM ICCID')),
                ('imsi', models.CharField(blank=True, max_length=40, verbose_name='SIM IMSI')),
                ('meter_type', models.CharField(blank=True, max_length=100, verbose_name='Hisoblagich turi')),
                ('meter_serial', models.CharField(blank=True, max_length=100, verbose_name='Hisoblagich seriyasi')),
                ('boot_count', models.PositiveIntegerField(default=0, verbose_name='Yuklanishlar soni')),
                ('first_boot_at', models.DateTimeField(blank=True, null=True)),
                ('last_boot_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_status', models.CharField(blank=True, max_length=40)),
                ('firmware_status_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostics_status', models.CharField(blank=True, max_length=40)),
                ('diagnostics_status_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='stations.station')),
            ],
            options={
                'verbose_name': 'Qurilma pasporti',
                'verbose_name_plural': 'Qurilma pasportlari',
            },
        ),
        migrations.CreateModel(
            name='ChargerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('is_readonly', models.BooleanField(default=False)),
                ('is_unknown', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='stations.station')),
            ],
            options={
                'verbose_name': 'Qurilma sozlamasi',
                'verbose_name_plural': 'Qurilma sozlamalari',
                'ordering': ['key'],
                'unique_together': {('station', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ChargerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('boot', 'Yuklanish'), ('status', 'Holat xabari'), ('stop', 'Sessiya tugadi'), ('firmware', 'Proshivka'), ('diagnostics', 'Diagnostika'), ('error', 'Nosozlik'), ('other', 'Boshqa')], default='other', max_length=12)),
                ('action', models.CharField(blank=True, help_text='OCPP action nomi', max_length=50)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stations.station')),
            ],
            options={
                'verbose_name': 'Qurilma jurnali',
                'verbose_name_plural': 'Qurilma jurnali',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['station', '-created_at'], name='stations_ch_station_2ec8e8_idx')],
            },
        ),
    ]
