# Generated by Django 5.1.15 on 2026-08-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_chargerinfo_chargerconfiguration_chargerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='power_limit_kw',
            field=models.PositiveIntegerField(blank=True, help_text="Qurilmaga yuborilgan chegara. Bo'sh — cheklovsiz.", null=True, verbose_name='Quvvat chegarasi (kVt)'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='status',
            field=models.CharField(choices=[('available', "Bo'sh"), ('charging', 'Zaryadlanmoqda'), ('reserved', 'Bron qilingan'), ('offline', 'Ishlamayapti')], default='available', max_length=10),
        ),
    ]
