# Generated by Django 5.1.15 on 2026-08-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_connector_power_limit_kw_alter_connector_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Tungi tarif', max_length=100, verbose_name='Nomi')),
                ('start_time', models.TimeField(verbose_name='Boshlanishi')),
                ('end_time', models.TimeField(verbose_name='Tugashi')),
                ('day_kind', models.CharField(choices=[('every', 'Har kuni'), ('workday', 'Ish kunlari'), ('weekend', 'Dam olish va bayram')], default='every', max_length=10, verbose_name='Kunlar')),
                ('price_per_kwh', models.PositiveIntegerField(verbose_name="Narx (so'm/kVt·s)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, help_text="Bo'sh — barcha stansiyalarda amal qiladi", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_windows', to='stations.station', verbose_name='Stansiya')),
            ],
            options={
                'verbose_name': 'Tarif oynasi',
                'verbose_name_plural': 'Tarif oynalari',
                'ordering': ['start_time', 'name'],
            },
        ),
    ]
