# Generated by Django 5.1.15 on 2026-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_tariffwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='ocpp_password',
            field=models.CharField(blank=True, help_text='Charger sozlamasiga ham xuddi shu parol kiritiladi', max_length=100, verbose_name='OCPP paroli'),
        ),
    ]
