# Generated by Django 5.1.15 on 2026-09-01 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_station_ocpp_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='source',
            field=models.CharField(choices=[('ocpp', 'Qurilmadan'), ('manual', "Qo'lda"), ('user', 'Foydalanuvchidan')], default='ocpp', max_length=8),
        ),
        migrations.CreateModel(
            name='StationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='stations.maintenanceissue')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi xabari',
                'verbose_name_plural': 'Foydalanuvchi xabarlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['station', '-created_at'], name='stations_st_station_7bfc74_idx')],
            },
        ),
    ]
