# Generated by Django 5.1.15 on 2026-08-31 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_usernotification_push_attempts_and_more'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name="Summa (so'm)")),
                ('state', models.IntegerField(choices=[(0, 'Yaratildi'), (1, 'Kutilmoqda'), (2, "To'landi"), (-1, 'Bekor qilindi'), (-2, 'Qaytarildi')], default=0)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Tashqi ID')),
                ('prepare_id', models.CharField(blank=True, max_length=64)),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('cancel_reason', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='management.paymentprovider', verbose_name="To'lov tizimi")),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov buyurtmasi",
                'verbose_name_plural': "To'lov buyurtmalari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='wallet_paym_provide_4bc658_idx')],
            },
        ),
    ]
