# Generated by Django 5.2.17 on 2026-09-01 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_sitesettings_mail_alerts_to_and_more'),
        ('wallet', '0002_paymentorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='is_auto',
            field=models.BooleanField(default=False, verbose_name='Avtomatik'),
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_encrypted', models.TextField(blank=True, verbose_name='Token (shifrlangan)')),
                ('verify_ref', models.CharField(blank=True, max_length=120)),
                ('masked_pan', models.CharField(max_length=24, verbose_name='Karta')),
                ('brand', models.CharField(blank=True, max_length=20, verbose_name='Turi')),
                ('expires', models.CharField(blank=True, help_text='MM/YY', max_length=5, verbose_name='Amal muddati')),
                ('state', models.IntegerField(choices=[(0, 'Tasdiqlanmagan'), (1, 'Faol'), (2, 'Ishlamaydi')], default=0)),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy karta')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='management.paymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biriktirilgan karta',
                'verbose_name_plural': 'Biriktirilgan kartalar',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yoqilgan')),
                ('threshold', models.PositiveIntegerField(default=20000, help_text='Balans shundan pasaysa to‘ldiriladi', verbose_name="Chegara (so'm)")),
                ('amount', models.PositiveIntegerField(default=50000, verbose_name="Har safar (so'm)")),
                ('daily_limit', models.PositiveIntegerField(default=200000, verbose_name="Kunlik chegara (so'm)")),
                ('monthly_limit', models.PositiveIntegerField(default=1000000, verbose_name="Oylik chegara (so'm)")),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('fail_streak', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_topup', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_topups', to='wallet.savedcard')),
            ],
            options={
                'verbose_name': 'Avtomatik to‘ldirish',
                'verbose_name_plural': 'Avtomatik to‘ldirish',
            },
        ),
    ]
