# Generated by Django 5.1.15 on 2026-08-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ocpp_reservation_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
